"""empty message

Revision ID: 40547f81acf3
Revises: 
Create Date: 2024-11-04 00:33:15.835593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40547f81acf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ind_or_group', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('AnimalSpecies', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('AnimalBreed', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('AnimalColour', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('AnimalName', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('AnimalGender', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('Measure', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ComplexDate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('AnimalKeepingLocation', sa.String(length=250), nullable=True))
        batch_op.drop_column('Ind_or_Group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Ind_or_Group', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
        batch_op.drop_column('AnimalKeepingLocation')
        batch_op.drop_column('ComplexDate')
        batch_op.drop_column('Measure')
        batch_op.drop_column('AnimalGender')
        batch_op.drop_column('AnimalName')
        batch_op.drop_column('AnimalColour')
        batch_op.drop_column('AnimalBreed')
        batch_op.drop_column('AnimalSpecies')
        batch_op.drop_column('Ind_or_group')

    # ### end Alembic commands ###
